name: NASA Project CI
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js version 16
      - uses: actions/setp-node@v2
      - run: |
          npm install 
          npm run build --prefix client
